#!/usr/bin/env python3
from flet import app, TextField, Text, Column, Row, Page, ElevatedButton, colors



def logged_view(page):
    return view

def login_view(page):
    view = Column()
    email = Column()
    emaillabel = Text(value='Email')
    emailInput = TextField(label='Email')
    email.controls=[emaillabel,emailInput]
    email.horizontal_alignment = "center"
    pwd = Column()
    pwdlabel = Text(value='pwd')
    pwdInput = TextField(label='pwd',password=True)
    pwd.controls=[pwdlabel,pwdInput]
    pwd.horizontal_alignment = "center"
    view.controls = [email,pwd]
    return view


views = {
    "/login": login_view,
    "/home": logged_view
}


def  refresh_view(page):
    page.clean()
    page.add(views[actual_view](page))

def refresh_page(page):
    page.update()

def view_exists(view):
    return view in views

def update_actual_view(view):
    if view_exists(view) : actual_view = view




actual_view = '/login'

def app_loop(page: Page):
    page.vertical_alignment = "center"
    if view_exists(actual_view):
        refresh_view(page)

app(target=app_loop)

